# Generated by Django 3.0.14 on 2023-03-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230303_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='full_name',
            new_name='username',
        ),
    ]
