# Generated by Django 4.1.7 on 2023-03-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_usercourseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseenrollment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='main.course'),
        ),
    ]
