# Generated by Django 4.1.7 on 2023-04-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_studentfavoritecourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfavoritecourse',
            options={'verbose_name_plural': '7. User Favorite Courses'},
        ),
    ]
