# Generated by Django 4.1.7 on 2023-04-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_studentfavoritecourse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='user_profile_imgs/'),
        ),
    ]
