# Generated by Django 4.1.7 on 2023-04-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_attemptquiz_right_ans_alter_attemptquiz_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'verbose_name_plural': '10. Course Quizzes'},
        ),
    ]
