# Generated by Django 4.1.7 on 2023-04-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_attemptquiz_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptquiz',
            name='quiz',
        ),
    ]
