# Generated by Django 4.1.7 on 2023-04-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_student_login_via_otp_teacher_login_via_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='login_via_otp',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='login_via_otp',
        ),
    ]
