# Generated by Django 4.1.7 on 2023-04-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_teacheruserchant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherUserChant',
            new_name='TeacherUserChat',
        ),
    ]
