# Generated by Django 4.1.7 on 2023-04-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_userassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassignment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='userassignment',
            name='user',
        ),
        migrations.AddField(
            model_name='userassignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
