# Generated by Django 4.1.7 on 2023-04-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_userassignment_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='upload',
            field=models.FileField(null=True, upload_to='assignments/'),
        ),
    ]
