# Generated by Django 4.1.7 on 2023-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_userassignment_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='video',
        ),
        migrations.AddField(
            model_name='chapter',
            name='upload',
            field=models.FileField(null=True, upload_to='chapter_materials/'),
        ),
    ]
