# Generated by Django 4.1.7 on 2023-04-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_student_sentwork_delete_sentwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sentwork',
        ),
    ]
